Repository appy-one/acebase, pull requests merged in 2023-07, with the labels that each got.

#234 Improvement: remove window references
  package-lock.json
  package.json
  src/browser.ts
  src/ipc/browser.ts
  src/query.ts
  src/storage/custom/indexed-db/index.ts
  src/storage/custom/local-storage/index.ts
Labels: enhancement, code quality

#232 Create new documentation site based on README
  docs/.nojekyll
  docs/README.md
  docs/favicon.ico
  docs/img/contribute.svg
  docs/img/logo.png
  docs/img/logo_no_bg.png
  docs/img/sponsor.svg
  docs/img/tweet.svg
  docs/index.html
Labels: enhancement, documentation

#230 Fix `target` of `mutations` events on wildcard paths
  src/storage/index.ts
  src/test/events.spec.ts
Labels: bug

#237 Add support for old Safari in webworker
  src/ipc/browser.ts
Labels: bug, browser
